export const FilterCards = [
  {
    title: "Tour class",
    id: 1,
    card: [
      { name: "Most popular", open: false, id: 1 },
      { name: "Trekking", open: false, id: 2 },
      { name: "Multi - active", open: false, id: 3 },
      { name: "Horse riding", open: false, id: 4 },
      { name: "Winter tours", open: false, id: 5 },
      { name: "Moto trip", open: false, id: 6 },
      { name: "Cultural", open: false, id: 7 },
      { name: "Road trip", open: false, id: 8 },
      { name: "Horse riding", open: false, id: 9 },
    ],
  },
  {
    title: "Places i want to visit",
    id: 2,
    card: [
      { name: "Cholpon - Ata", open: false, id: 1 },
      { name: "Bosteri", open: false, id: 2 },
      { name: "Ala - Archa", open: false, id: 3 },
      { name: "San - Tash", open: false, id: 4 },
      { name: "Akbulung", open: false, id: 5 },
      { name: "Batken", open: false, id: 6 },
      { name: "Bokonbay", open: false, id: 7 },
      { name: "Saimaluu - Tash", open: false, id: 8 },
      { name: "Kochkor", open: false, id: 9 },
      { name: "Arslanbob", open: false, id: 10 },
      { name: "Talas", open: false, id: 11 },
      { name: "Jalal - Abad", open: false, id: 12 },
      { name: "Karakol", open: false, id: 13 },
      { name: "Issik - Kol lake", open: false, id: 14 },
      { name: "Naryn town", open: false, id: 15 },
      { name: "Sary - Chelek lake", open: false, id: 16 },
      { name: "Osh town", open: false, id: 17 },
      { name: "Bishkek", open: false, id: 18 },
      { name: "Tash - Rabat Caravanserai", open: false, id: 19 },
      { name: "Song - kol lake", open: false, id: 20 },
      { name: "Kel - Suu lake", open: false, id: 21 },
    ],
  },
  {
    title: "Activities i want to do",
    id: 3,
    card: [
      { name: "Backpacking", open: false, id: 1 },
      { name: "Base Camp", open: false, id: 2 },
      { name: "Canoe", open: false, id: 3 },
      { name: "Rafting", open: false, id: 4 },
      { name: "Packraft", open: false, id: 5 },
      { name: "Horses", open: false, id: 6 },
      { name: "Photography", open: false, id: 7 },
      { name: "Custom", open: false, id: 8 },
    ],
  },
  {
    title: "Duration",
    id: 4,
    card: [
      { name: "1 day", open: false, id: 1 },
      { name: "2 days", open: false, id: 2 },
      { name: "3 days", open: false, id: 3 },
      { name: "4 days", open: false, id: 4 },
      { name: "5 days", open: false, id: 5 },
      { name: "6 days", open: false, id: 6 },
      { name: "7 days", open: false, id: 7 },
      { name: "8 days", open: false, id: 8 },
      { name: "9 days", open: false, id: 9 },
      { name: "10 days", open: false, id: 10 },
      { name: "11 days", open: false, id: 11 },
      { name: "12 days", open: false, id: 12 },
      { name: "13 days", open: false, id: 13 },
      { name: "14 days", open: false, id: 14 },
      { name: "15 days", open: false, id: 15 },
      { name: "16 days", open: false, id: 16 },
    ],
  },
];
